// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// one
double one(double x);
RcppExport SEXP _bedtorch_one(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(one(x));
    return rcpp_result_gen;
END_RCPP
}
// c_rollmean
NumericVector c_rollmean(NumericVector x, int k, bool na_pad, bool na_rm, int align);
RcppExport SEXP _bedtorch_c_rollmean(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP, SEXP alignSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type align(alignSEXP);
    rcpp_result_gen = Rcpp::wrap(c_rollmean(x, k, na_pad, na_rm, align));
    return rcpp_result_gen;
END_RCPP
}
// c_rollsum
NumericVector c_rollsum(NumericVector x, int k, bool na_pad, bool na_rm, int align);
RcppExport SEXP _bedtorch_c_rollsum(SEXP xSEXP, SEXP kSEXP, SEXP na_padSEXP, SEXP na_rmSEXP, SEXP alignSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type na_pad(na_padSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type align(alignSEXP);
    rcpp_result_gen = Rcpp::wrap(c_rollsum(x, k, na_pad, na_rm, align));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bedtorch_one", (DL_FUNC) &_bedtorch_one, 1},
    {"_bedtorch_c_rollmean", (DL_FUNC) &_bedtorch_c_rollmean, 5},
    {"_bedtorch_c_rollsum", (DL_FUNC) &_bedtorch_c_rollsum, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bedtorch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
