# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_tabix <- function(file_path) {
    .Call(`_bedtorch_test_tabix`, file_path)
}

c_read_tabix_table <- function(file_path, regions, output_file, index_path, download_index = FALSE) {
    invisible(.Call(`_bedtorch_c_read_tabix_table`, file_path, regions, output_file, index_path, download_index))
}

c_rollmean <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = 1L) {
    .Call(`_bedtorch_c_rollmean`, x, k, na_pad, na_rm, align)
}

c_rollsum <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = 1L) {
    .Call(`_bedtorch_c_rollsum`, x, k, na_pad, na_rm, align)
}

