# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_read_tabix_table <- function(file_path, regions, output_file, index_path, download_index = FALSE) {
    invisible(.Call(`_bedtorch_c_read_tabix_table`, file_path, regions, output_file, index_path, download_index))
}

c_rollmean <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = 1L) {
    .Call(`_bedtorch_c_rollmean`, x, k, na_pad, na_rm, align)
}

c_rollsum <- function(x, k, na_pad = FALSE, na_rm = FALSE, align = 1L) {
    .Call(`_bedtorch_c_rollsum`, x, k, na_pad, na_rm, align)
}

bgzip <- function(input_file_path, output_file_path, append = FALSE) {
    invisible(.Call(`_bedtorch_bgzip`, input_file_path, output_file_path, append))
}

build_tabix_index <- function(file_path) {
    invisible(.Call(`_bedtorch_build_tabix_index`, file_path))
}

